### ISSUE TITLE
Plans for postgres

### ISSUE THREAD

**Issue by marcin-bury** [solmanter/nestjs-drizzle#2]
Hi

What are the plans for postgresjs drizzle driver? Any timetable?

TIA
Marcin

**Comment by solmanter** [comment]
very soon

**Comment by marcin-bury** [comment]
Hi
Thx for postgres module
Do you have, by a chance, working nestjs sample app with this module? I.m getting '(0 , postgres_1.default) is not a function' error
 when app starts . Since I'm new to nestjs, apparently doing something wrong.
Also pls review your readme "for async registration" section. I had to add missing schema parameter. Maybe I did not do it in proper way.

**Comment by solmanter** [comment]
what is your node version?

**Comment by marcin-bury** [comment]
20.10.0
dependencies": {
    "@nestjs/common": "^10.3.1",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.3.1",
    "@nestjs/platform-express": "^10.3.1",
    "drizzle-orm": "^0.29.3",
    "postgres": "^3.4.3",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^7.8.1"
  }

**Comment by solmanter** [comment]
where is nestjs-drizzle?
try this
```bash
npm remove --purge nestjs-drizzle
npm install nestjs-drizzle
```

**Comment by marcin-bury** [comment]
actually I copied this four units from postgres folder instead of installing the package.
It seemed to be better options since I would prefer using Options object for postgres() method

**Comment by solmanter** [comment]
I don't fully understand what you did, but you can solve the problem by reading the documentation.

**Comment by marcin-bury** [comment]
This should not be a problem, I assumed 
However I will try again, this time "by the book" and let you know

**Comment by marcin-bury** [comment]
import { DrizzleModule, registerAsync } from 'nestjs-drizzle/postgres'; <- vs code reports problem here
Module '"nestjs-drizzle/postgres"' has no exported member 'registerAsync'.

When I have removed problematic import - I was able to start nest application.
I wonder what I did wrong.

Apart from that, do you consider extending the module to accept postgres.Options object?

**Comment by solmanter** [comment]
yes, last update i remove registerAsync, i forget to remove from docs! now you can do like this
```ts
import { DrizzleModule } from 'nestjs-drizzle/postgres';
import * as schema from 'src/drizzle/schema'

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    DrizzleModule.forAsyncRoot({
      isGlobal: true,
      useFactory: async (config: ConfigService) => ({
        connection: config.get('DATABASE_URL'),
        schema,
      }),
      inject: [ConfigService]
    }),
  ]
})
```
> DATABASE_URL -> `postgresql://USER:PASSWORD@HOST:PORT/DB`

**Comment by marcin-bury** [comment]
What about postgres.Options?
This would make the module more flexible if the user would like to provide extra parameters like ssl / max(connections) / debug etc.

**Comment by solmanter** [comment]
maybe later

**Comment by marcin-bury** [comment]
Ok
Thanks for the support, issue to close...
